### ISSUE TITLE
Location of assets

### ISSUE THREAD

**Issue by schwittlick** [codeanticode/processing-android-3.0-samples#1]
Hey there,

super helpful stuff in your examples. This really makes it great to work on tablets with Processing when using a big IDE. 

Do you have an example that loads a file, like an image. I'm wondering where Processing's data folder would need to go if I want to use images. Somehow I tried everything on Windows 10 / Android Studio / Android 5.0.2, API 21 and no place seems to work.

```
PImage buttonImage = loadImage("button.png");
```

At all these places the file could not be found. And i made sure the file is not corrupted or anything.

```
processing-android-3.0-samples\androidstudio-sample\button.png
processing-android-3.0-samples\androidstudio-sample\app\button.png
processing-android-3.0-samples\androidstudio-sample\app\data\button.png
processing-android-3.0-samples\androidstudio-sample\app\src\main\res\button.png
processing-android-3.0-samples\androidstudio-sample\app\src\main\res\drawable\button.png
```

I don't have any Android development experience so I might be missing something super simple?

Thanks already,
Marcel

**Comment by codeanticode** [comment]
Hi sorry, for the delayed response. You might have solved this already, but answering your question,  in Android Studio you have to put the image file in the assets folder inside app/src/main, you can use the assistant inside the IDE to create it: http://code2care.org/2015/create-assets-folder-in-android-studio/
